"""Add town country and phone

Revision ID: 4b390636d38c
Revises: 
Create Date: 2025-07-12 14:21:06.151842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b390636d38c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('town', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('country')
        batch_op.drop_column('town')

    # ### end Alembic commands ###
